service: test

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-northeast-1

plugins:
  localPath: '../../'
  modules:
    - serverless-diffs

functions:
  hello:
    handler: handler.hello
    # timeout: 20
    memory: 1020

  world:
    handler: handler.hello
    # timeout: 20
    memory: 1020
